### ISSUE TITLE
Usabilidade imediata/pré requisitos

### ISSUE THREAD

**Issue by edc0** [AutomatexDev/automatex2#4]
tive q baixar o texlive-luatex e o livetex-xetex (por enquanto) pra fazer funcionar. não é melhor algo que funcione direto quando o cara baixa o livetex? ou eu fui noob?

quais seriam as implicações e mudanças necessárias?

**Comment by edc0** [comment]
caceta, agora preciso instalar isso aqui, aparentemente:
https://github.com/wspr/unicode-math

cansei

**Comment by alexandrelheinen** [comment]
O Luatex/Xetex (não sei porque Xetex) é necessário para compilar as fontes externas. Se por acaso formos usar uma fonte do Font Catalog, daí não vai precisar desses pacotes. Mesma coisa pra unicode-math.

No Linux, se tu não tiver com problemas de espaço de armazenamento, só dá um
```sudo apt-get install texlive-full```

Ele instala todos os pacotes do Latex, dá uns 3Gb, ou algo assim.

**Comment by edc0** [comment]
de fato, instalando o texlive-full resolveu... acho meio bobo, mas deixa pro pessoal do automatex3 resolver
