### ISSUE TITLE
Como escrever teu TCC com o automatex.cls em uma pasta separada

### ISSUE THREAD

**Issue by alexandrelheinen** [AutomatexDev/automatex2#6]
@edc0, de acordo com [esse cara](http://www.math.illinois.edu/~ajh/tex/tips-customstyles.html), o TeX tem algumas pastas onde ele procura por estilo, classes...

No caso das classes de documento, o diretório é `$HOME/texmf/tex/latex/`. Assim é fácil fazer com que o latex utilize sempre o automatex sem que ele esteja na mesma pasta.

A solução que eu prefiro é criar um link simbólico para o `automatex.cls` dentro do diretório, ou seja, criar essas pastas caso elas não existam e então estabelecer o link, por exemplo,
```shell
cd $HOME/texmf/tex/latex/
ln -s $HOME/automatex2/automatex.cls ./automatex.cls
```

**Comment by edc0** [comment]
@alexandrelheinen bah, o link simbólico vai ferrar pra quem não usa linux... mas na real acho que não é mais necessário isso, pois uma vez que o template estiver estável, o user só copia ele pra sua pasta de trabalho e não encosta mais em nada. aliás, melhor mesmo que ninguém mexa.

levei meses pra aprender isso. vou fechar o issue.
